config/routes.rb
Rails.application.routes.draw do

  root 'notams#index'

  resources :notam, :only => [:index]

  post 'notams/output' => 'notams#output'

end

app/models/notam.rb
class Notam < ActiveRecord::Base

	def self.days_array
		days = []
		Date::DAYNAMES.each_with_index { |x, i| days << x[0..2].upcase }
		return days
	end

	def self.get_extra_time_if_exists arr
		value =  arr[0]
		value = value + " #{arr[1]}"  if !arr[1].blank? && arr[1][0..2].to_i != 0
		return value
	end

	def self.return_correct_notams input
		notam_arr = Array.new
		input.split("\n\r").each do |n|
			notam_arr << n.gsub(/[^0-9a-z )-]/i, ' ').split("A) ")[1] if n.include? 'AERODROME HOURS OF OPS/SERVICE'
		end
		
		notam_arr.collect! {|x| x = x.split(' CREATED')[0] }

		details_array = Array.new
		notam_arr.each do |n|
			times_hash = Hash.new { |hash, key| hash["ICAO"] = n[0..4] }
			days_array.each do |d|
				if n.include?(d)
					from_index = n.index(d)
					if n[from_index + 3] == '-'
						next_space = n[from_index+7..n.size].split(' ')
						value = get_extra_time_if_exists next_space
						days_array[days_array.index(d)..days_array.index(n[from_index+4..from_index + 6])].each do |i|
							times_hash[i] = value
						end
					else
						next_space = n[from_index+3..n.size].split(' ')
						value = get_extra_time_if_exists next_space
					end
					times_hash[d] = value
				end
			end
			details_array << times_hash
		end
		return details_array
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notams_controller.rb
class NotamsController < ApplicationController
  def index
  end

  def output
  	@notams = Notam.return_correct_notams params[:input]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notams_helper.rb
module NotamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stratajet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<h1>Stratajet Code Test</h1>
<%= yield %>
</div>

</body>
</html>

app/views/notams/index.html.erb
<h4>Input a NOTAM text string</h4>
<%= form_tag(notams_output_path, method: "post") do %>
	<div class="form-group">
		<%= text_area_tag :input, nil, :class => 'form-control' %>
	</div>
	<div class="form-group">
		<%= submit_tag 'Submit', :class => 'btn btn-info' %>
	</div>
<% end %>

app/views/notams/output.html.erb
<h4>Notam output:</h4>
<table class="table table-condensed">
	<thead>
		<th>
			ICAO
		</th>
		<th>
			Monday
		</th>
		<th>
			Tuesday
		</th>
		<th>
			Wednesday
		</th>
		<th>
			Thursday
		</th>
		<th>
			Friday
		</th>
		<th>
			Saturday
		</th>
		<th>
			Sunday
		</th>
	</thead>
	<tbody>
		<% @notams.each do |n| %>
			<tr>
				<td>
					<%= n["ICAO"] %>
				</td>
				<td>
					<%= n["MON"] %>
				</td>
				<td>
					<%= n["TUE"] %>
				</td>
				<td>
					<%= n["WED"] %>
				</td>
				<td>
					<%= n["THU"] %>
				</td>
				<td>
					<%= n["FRI"] %>
				</td>
				<td>
					<%= n["SAT"] %>
				</td>
				<td>
					<%= n["SUN"] %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Back", root_path, :class => 'btn btn-info' %>